In [1]:
# Dataset A: https://drive.google.com/file/d/1xaj40SRwgcabIxsV1SeNKv2M4UtI3h80/view?usp=share_link
!gdown 1xaj40SRwgcabIxsV1SeNKv2M4UtI3h80

Downloading...
From: https://drive.google.com/uc?id=1xaj40SRwgcabIxsV1SeNKv2M4UtI3h80
To: /content/IMDB-Movie-Data.csv
100% 310k/310k [00:00<00:00, 31.7MB/s]

In [2]:
!pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.13.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

1. Import libraries v√† load dataset:

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset_path = '/content/IMDB-Movie-Data.csv'
data = pd.read_csv(dataset_path)

In [4]:
data_indexed = pd.read_csv(dataset_path, index_col="Title")
data

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

2. View the data:

In [5]:
data.head()  # Hi·ªÉn th·ªã 5 d√≤ng ƒë·∫ßu ti√™n c·ªßa d·ªØ li·ªáu

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

3. Understand some basic information about the data:

In [6]:
data.info()  # Th√¥ng tin t·ªïng quan v·ªÅ d·ªØ li·ªáu

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [7]:
data.describe()  # Th·ªëng k√™ c∆° b·∫£n v·ªÅ d·ªØ li·ªáu

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

4. Data Selection ‚Äì Indexing and Slicing data:

In [8]:
# Extract data as series
genre = data['Genre']
genre

0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
                 ...
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy
Name: Genre, Length: 1000, dtype: object

In [9]:
# Extract data as dataframe
data [['Genre']]

                        Genre
0     Action,Adventure,Sci-Fi
1    Adventure,Mystery,Sci-Fi
2             Horror,Thriller
3     Animation,Comedy,Family
4    Action,Adventure,Fantasy
..                        ...
995       Crime,Drama,Mystery
996                    Horror
997       Drama,Music,Romance
998          Adventure,Comedy
999     Comedy,Family,Fantasy

[1000 rows x 1 columns]

In [10]:
some_cols = data[['Title', 'Genre', 'Actors', 'Director', 'Rating']]
print(some_cols)

                       Title                     Genre  \
0    Guardians of the Galaxy   Action,Adventure,Sci-Fi
1                 Prometheus  Adventure,Mystery,Sci-Fi
2                      Split           Horror,Thriller
3                       Sing   Animation,Comedy,Family
4              Suicide Squad  Action,Adventure,Fantasy
..                       ...                       ...
995     Secret in Their Eyes       Crime,Drama,Mystery
996          Hostel: Part II                    Horror
997   Step Up 2: The Streets       Drama,Music,Romance
998             Search Party          Adventure,Comedy
999               Nine Lives     Comedy,Family,Fantasy

                                                Actors              Director  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...            James Gunn
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...          Ridley Scott
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...    M. Night Shyamalan
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  Christophe Lourdelet
4    Will Smith, Jared Leto, Margot Robbie, Viola D...            David Ayer
..                                                 ...                   ...
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...             Billy Ray
996  Lauren German, Heather Matarazzo, Bijou Philli...              Eli Roth
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...            Jon M. Chu
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...        Scot Armstrong
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...      Barry Sonnenfeld

     Rating
0       8.1
1       7.0
2       7.3
3       7.2
4       6.2
..      ...
995     6.2
996     5.5
997     6.2
998     5.6
999     5.3

[1000 rows x 5 columns]

In [11]:
data.iloc[10:15][['Title', 'Rating', 'Revenue (Millions)']]

                                      Title  Rating  Revenue (Millions)
10  Fantastic Beasts and Where to Find Them     7.5              234.02
11                           Hidden Figures     7.8              169.27
12                                Rogue One     7.9              532.17
13                                    Moana     7.7              248.75
14                                 Colossal     6.4                2.87

5. Data Selection ‚Äì Based on Conditional filtering:

In [12]:
filtered_data = data[((data['Year'] >= 2010) & (data['Year'] <= 2015))
                    & (data['Rating'] < 6.0)
                    & (data['Revenue (Millions)'] > data['Revenue (Millions)'].quantile(0.95))]
print(filtered_data)

     Rank                       Title                    Genre  \
941   942  The Twilight Saga: Eclipse  Adventure,Drama,Fantasy

                                           Description     Director  \
941  As a string of mysterious killings grips Seatt...  David Slade

                                                Actors  Year  \
941  Kristen Stewart, Robert Pattinson, Taylor Laut...  2010

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
941                124     4.9  192740              300.52       58.0

6. Groupby Operations:

In [13]:
result = data.groupby('Director')[['Rating']].mean().head()
print(result)

                     Rating
Director
Aamir Khan              8.5
Abdellatif Kechiche     7.8
Adam Leon               6.5
Adam McKay              7.0
Adam Shankman           6.3

7. Sorting Operations:

In [14]:
result = data.groupby('Director')[['Rating']].mean().sort_values(['Rating'], ascending=False).head()
print(result)

                   Rating
Director
Nitesh Tiwari        8.80
Christopher Nolan    8.68
Olivier Nakache      8.60
Makoto Shinkai       8.60
Aamir Khan           8.50

8. View missing values:

In [15]:
missing_values = data.isnull().sum()
print(missing_values)

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

9. Deal with missing values - Deleting

In [16]:
data = pd.read_csv('/content/IMDB-Movie-Data.csv')

In [17]:
data.drop('Metascore', axis=1).head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions)
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02

In [18]:
data.dropna()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

10. Dealing with missing values - Filling:

In [19]:
revenue_mean = data_indexed['Revenue (Millions)'].mean()
print("The mean revenue is:", revenue_mean)

data_indexed['Revenue (Millions)'].fillna(revenue_mean, inplace=True)

print(data_indexed.head())

The mean revenue is: 82.95637614678898
                         Rank                     Genre  \
Title
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi
Prometheus                  2  Adventure,Mystery,Sci-Fi
Split                       3           Horror,Thriller
Sing                        4   Animation,Comedy,Family
Suicide Squad               5  Action,Adventure,Fantasy

                                                               Description  \
Title
Guardians of the Galaxy  A group of intergalactic criminals are forced ...
Prometheus               Following clues to the origin of mankind, a te...
Split                    Three girls are kidnapped by a man with a diag...
Sing                     In a city of humanoid animals, a hustling thea...
Suicide Squad            A secret government agency recruits some of th...

                                     Director  \
Title
Guardians of the Galaxy            James Gunn
Prometheus                       Ridley Scott
Split                      M. Night Shyamalan
Sing                     Christophe Lourdelet
Suicide Squad                      David Ayer

                                                                    Actors  \
Title
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...

                         Year  Runtime (Minutes)  Rating   Votes  \
Title
Guardians of the Galaxy  2014                121     8.1  757074
Prometheus               2012                124     7.0  485820
Split                    2016                117     7.3  157606
Sing                     2016                108     7.2   60545
Suicide Squad            2016                123     6.2  393727

                         Revenue (Millions)  Metascore
Title
Guardians of the Galaxy              333.13       76.0
Prometheus                           126.46       65.0
Split                                138.12       62.0
Sing                                 270.32       59.0
Suicide Squad                        325.02       40.0

11. apply() functions:

In [20]:
# Classify movies based on ratings
def rating_group(rating):
    if rating >= 7.5:
        return 'Good'
    elif rating >= 6.0:
        return 'Average'
    else:
        return 'Bad'

data['Rating_category'] = data['Rating'].apply(rating_group)
print(data[['Title', 'Director', 'Rating', 'Rating_category']].head(5))

                     Title              Director  Rating Rating_category
0  Guardians of the Galaxy            James Gunn     8.1            Good
1               Prometheus          Ridley Scott     7.0         Average
2                    Split    M. Night Shyamalan     7.3         Average
3                     Sing  Christophe Lourdelet     7.2         Average
4            Suicide Squad            David Ayer     6.2         Average